# -*- coding: utf-8 -*-
"""Phần bổ sung theo ngôn ngữ cho từng mẫu:
  cpp  – giải thích code C++ (ngôn ngữ chính của khóa)
  py   – giải thích code Python
  emb  – áp dụng trong lập trình nhúng (Arduino / ESP32 / STM32 / FreeRTOS)
  cpp_real, py_real – gặp ở đâu trong thư viện thực tế
"""

LANG = {
"singleton": dict(
  cpp=["<code>AppConfig::getInstance()</code> dùng <b>Meyers Singleton</b>: biến <code>static</code> cục bộ được chuẩn C++11 đảm bảo khởi tạo đúng 1 lần và thread-safe.",
       "<code>= delete</code> copy constructor và phép gán → dòng <code>AppConfig y = c1;</code> sẽ <b>lỗi ngay lúc biên dịch</b>, không đợi tới lúc chạy.",
       "<code>Uart0</code> mô phỏng driver ngoại vi: <code>std::call_once</code> đảm bảo <code>initHardware()</code> chạy đúng 1 lần dù 50 luồng gọi đồng thời.",
       "Đối tượng nằm ở vùng nhớ tĩnh (<code>.bss</code>/<code>.data</code>) chứ không phải heap — quan trọng với MCU có RAM nhỏ."],
  py=["Cách 1 ghi đè <code>__new__</code> + khoá <code>threading.Lock</code> (double-checked locking).",
      "Cách 2 dùng <b>metaclass</b> <code>SingletonMeta</code> — tái sử dụng cho nhiều lớp; <code>__init__</code> chỉ chạy một lần.",
      "Cách “Pythonic” nhất: đặt trạng thái trong một <b>module</b> (<code>config.py</code>) — module chỉ được import một lần."],
  emb=["Mỗi ngoại vi phần cứng là duy nhất (UART0, bus I2C, SPI, bộ ADC) → lớp driver của nó nên là Singleton để tránh hai nơi cùng cấu hình thanh ghi.",
       "Arduino làm sẵn điều này: <code>Serial</code>, <code>Wire</code>, <code>SPI</code>, <code>WiFi</code> là các đối tượng toàn cục duy nhất.",
       "Tránh khởi tạo phần cứng trong constructor của đối tượng toàn cục (chạy trước <code>main()</code>/<code>setup()</code>, khi clock chưa cấu hình xong) — dùng hàm <code>begin()</code>.",
       "Trên FreeRTOS: nếu nhiều task cùng dùng Singleton, bảo vệ dữ liệu bên trong bằng mutex."],
  cpp_real=["Arduino: <code>Serial</code>, <code>Wire</code>, <code>WiFi</code>, <code>EEPROM</code>", "ESP-IDF: <code>esp_event_loop</code> mặc định", "<code>std::cout</code> — đối tượng luồng xuất duy nhất"],
  py_real=["Module Python (mọi lần <code>import</code> trả về cùng đối tượng module)", "<code>logging.getLogger(name)</code>", "<code>None</code>, <code>True</code>, <code>False</code>"],
),
"factory-method": dict(
  cpp=["<code>createNotification()</code> là hàm <b>thuần ảo</b> (<code>= 0</code>) trả về <code>std::unique_ptr&lt;Notification&gt;</code> — quyền sở hữu rõ ràng, không rò rỉ bộ nhớ.",
       "Lớp gốc có <code>virtual ~Notification() = default;</code> — bắt buộc khi xoá đối tượng con qua con trỏ lớp cha.",
       "Mảng <code>NotificationService* services[]</code> cấp phát tĩnh, chỉ đối tượng sản phẩm mới tạo bằng <code>make_unique</code>.",
       "Lưu ý: <code>substr(0, 30)</code> cắt theo <b>byte</b>, có thể cắt đôi một ký tự UTF-8 tiếng Việt — vì vậy thông điệp mẫu viết không dấu."],
  py=["<code>abc.ABC</code> + <code>@abstractmethod</code> khiến lớp con quên cài đặt factory method sẽ báo lỗi ngay khi tạo đối tượng.",
      "Vì lớp trong Python là đối tượng, một <code>dict</code> ánh xạ tên → lớp đã là “simple factory” rất gọn."],
  emb=["Firmware hỗ trợ nhiều phiên bản phần cứng: <code>createSensor()</code> trả về <code>Dht22Sensor</code> hay <code>Sht31Sensor</code> tuỳ chân cấu hình hoặc giá trị trong EEPROM.",
       "Trên MCU nên tránh <code>new</code> lúc chạy: factory có thể trả về tham chiếu tới đối tượng tĩnh đã tạo sẵn, hoặc dùng <i>placement new</i> vào buffer tĩnh.",
       "Có thể thay đa hình lúc chạy bằng <code>#if</code>/template để chọn lúc biên dịch khi phần cứng cố định."],
  cpp_real=["<code>std::make_unique</code>, <code>std::make_shared</code>", "Qt: <code>QStyleFactory::create()</code>", "Arduino: <code>WiFiClient</code>/<code>WiFiClientSecure</code> tạo theo cấu hình"],
  py_real=["<code>logging.getLogger()</code>", "<code>open()</code> trả về <code>TextIOWrapper</code> hay <code>BufferedReader</code> tuỳ chế độ", "<code>collections.namedtuple()</code> tạo lớp mới"],
),
"abstract-factory": dict(
  cpp=["Các hàm tạo đều <code>const</code> và trả về <code>std::unique_ptr</code> của interface tương ứng.",
       "<code>render(const UIFactory&amp;)</code> nhận tham chiếu — không cần biết factory cụ thể, không cấp phát cho factory.",
       "Đổi họ sản phẩm chỉ bằng việc truyền đối tượng factory khác."],
  py=["Factory được chọn qua <code>dict</code> theo tên chủ đề — dễ đọc từ file cấu hình JSON.",
      "Python dùng duck typing nên không bắt buộc ABC, nhưng ABC giúp phát hiện sớm lớp thiếu phương thức."],
  emb=["Một firmware chạy trên nhiều board: <code>Esp32Factory</code> tạo <code>Esp32Gpio</code> + <code>Esp32Adc</code> + <code>Esp32Pwm</code>; <code>Stm32Factory</code> tạo bộ tương ứng — các thành phần luôn cùng một nền tảng.",
       "Đây chính là ý tưởng của tầng <b>HAL</b> (Hardware Abstraction Layer).",
       "Nếu board được chọn lúc biên dịch, có thể dùng <code>using Factory = Esp32Factory;</code> + template để không tốn hàm ảo."],
  cpp_real=["STM32 HAL / CMSIS-Driver (mỗi dòng chip một bộ driver cùng interface)", "Qt: các plugin nền tảng (QPA)", "Thư viện đồ hoạ LVGL với nhiều driver màn hình"],
  py_real=["<code>sqlite3</code>/<code>psycopg2</code> theo chuẩn DB-API: <code>connect()</code> → <code>cursor()</code> cùng driver", "Tkinter <code>ttk</code> themes"],
),
"builder": dict(
  cpp=["Constructor của <code>Robot</code> là <code>private</code>; lớp lồng <code>Robot::Builder</code> được truy cập vì lớp lồng có quyền với thành viên private của lớp bao.",
       "Mỗi hàm trả về <code>Builder&amp;</code> → gọi nối tiếp <code>.wheels(4).addSensor(...)</code>.",
       "<code>build()</code> trả về <code>std::optional&lt;Robot&gt;</code>: rỗng khi cấu hình sai — phù hợp firmware biên dịch với <code>-fno-exceptions</code>.",
       "<code>std::move</code> tránh sao chép chuỗi thừa."],
  py=["<code>@dataclass(frozen=True)</code> tạo lớp sản phẩm bất biến chỉ với vài dòng.",
      "Mỗi phương thức <code>return self</code> để gọi nối tiếp, đặt cả biểu thức trong ngoặc để xuống dòng.",
      "<code>build()</code> ném <code>ValueError</code> khi cấu hình sai."],
  emb=["Cấu hình ngoại vi có rất nhiều tham số: UART (baud, parity, stop bit, chân TX/RX), SPI, timer PWM… Builder giúp code cấu hình dễ đọc và kiểm tra hợp lệ trước khi ghi vào thanh ghi.",
       "Xây gói tin giao thức (Modbus, MQTT, CAN) từng trường một rồi <code>build()</code> tính checksum.",
       "ESP-IDF dùng struct cấu hình + designated initializer (<code>.baud_rate = 115200</code>) — một dạng “builder” kiểu C."],
  cpp_real=["<code>std::stringstream</code>", "ESP-IDF: <code>uart_config_t</code>, <code>wifi_config_t</code>", "Thư viện MQTT <code>PubSubClient</code> dựng gói CONNECT/PUBLISH"],
  py_real=["<code>argparse.ArgumentParser</code> thêm từng đối số", "SQLAlchemy <code>select().where().order_by()</code>", "<code>email.message.EmailMessage</code>"],
),
"prototype": dict(
  cpp=["<code>ExamPaper::clone()</code> chỉ cần <code>return *this;</code> — copy constructor mặc định đã sao chép sâu <code>std::vector</code> và <code>std::string</code>.",
       "Với cây kế thừa, C++ không có “virtual constructor” nên dùng hàm ảo <code>clone()</code> trả về <code>std::unique_ptr&lt;Shape&gt;</code> — đây chính là Prototype.",
       "<code>SensorBuffer</code> minh hoạ cạm bẫy: với <b>con trỏ thô</b>, copy mặc định chỉ chép địa chỉ → hai đối tượng dùng chung mảng (sửa <code>b</code> làm hỏng <code>a</code>, và nguy cơ double-free)."],
  py=["<code>copy.deepcopy</code> sao chép sâu toàn bộ đồ thị đối tượng; <code>copy.copy</code> chỉ sao chép nông.",
      "Ví dụ cho thấy rõ: bản shallow copy thêm câu hỏi làm đề gốc cũng tăng lên 3 câu."],
  emb=["Lưu sẵn “cấu hình mặc định” của thiết bị (ngưỡng, hệ số hiệu chuẩn) rồi clone ra để chỉnh cho từng kênh cảm biến.",
       "Clone gói tin mẫu (header cố định) rồi chỉ điền payload — nhanh hơn dựng lại từ đầu.",
       "Trên MCU: tránh clone ra heap; sao chép vào biến/stack hoặc vào slot của Object Pool."],
  cpp_real=["Copy constructor của mọi container STL", "Qt: <code>QObject</code> cố ý KHÔNG cho copy — ví dụ khi Prototype không phù hợp"],
  py_real=["Module <code>copy</code>", "<code>dict.copy()</code>, <code>list.copy()</code> (nông)"],
),
"object-pool": dict(
  cpp=["<code>ObjectPool&lt;T, N&gt;</code> là <b>template</b>: kích thước N biết lúc biên dịch, mọi đối tượng nằm trong <code>std::array</code> — <b>không có một lần cấp phát động nào</b>.",
       "<code>static ObjectPool pool;</code> đặt pool vào vùng nhớ tĩnh; kết quả <code>sizeof(pool)</code> cho biết chính xác RAM tiêu tốn.",
       "<code>acquire()</code> trả về <code>nullptr</code> khi đầy — firmware xử lý bằng cách bỏ qua hoặc thử lại ở vòng <code>loop()</code> sau.",
       "<code>release()</code> tính chỉ số bằng phép trừ con trỏ <code>obj - items_.data()</code>."],
  py=["<code>@contextmanager</code> cho phép viết <code>with pool.connection() as d:</code> — đối tượng <b>luôn được trả lại</b> kể cả khi có ngoại lệ.",
      "Trạng thái pool in ra trước và sau khối <code>with</code> cho thấy việc trả tự động."],
  emb=["Đây là mẫu <b>cực kỳ phổ biến</b> trong firmware: nhiều chuẩn an toàn (MISRA C++, AUTOSAR) cấm cấp phát động sau khi khởi động vì phân mảnh heap và thời gian không xác định.",
       "Ví dụ: pool buffer cho gói tin UART/CAN, pool khối nhớ cho hàng đợi FreeRTOS, pool sự kiện trong hệ thống event-driven.",
       "FreeRTOS cung cấp <code>xQueueCreateStatic</code>, <code>xTaskCreateStatic</code> — tạo đối tượng trên bộ nhớ tĩnh do bạn cấp."],
  cpp_real=["FreeRTOS: <code>heap_1</code>…<code>heap_5</code>, các API <code>...CreateStatic</code>", "Zephyr RTOS: <code>k_mem_slab</code>", "lwIP: <code>memp</code> pools cho pbuf/TCP PCB"],
  py_real=["<code>concurrent.futures.ThreadPoolExecutor</code>", "<code>multiprocessing.Pool</code>", "SQLAlchemy <code>QueuePool</code>"],
),
"adapter": dict(
  cpp=["Object Adapter giữ <b>tham chiếu</b> <code>UsFahrenheitSensor&amp;</code> — không sở hữu, không cấp phát.",
       "Class Adapter dùng <b>đa kế thừa</b>: <code>public TemperatureSensor</code> (lộ ra interface mới) và <code>private UsFahrenheitSensor</code> (chỉ mượn cài đặt, ẩn API cũ).",
       "Mảng <code>TemperatureSensor* sensors[]</code> chứa cả ba loại — client xử lý như nhau."],
  py=["Class Adapter trong Python cũng dùng đa kế thừa <code>class FahrenheitClassAdapter(TemperatureSensor, UsFahrenheitSensor)</code>.",
      "Do duck typing, đôi khi chỉ cần một hàm bọc nhỏ thay vì cả một lớp adapter."],
  emb=["Tình huống hằng ngày: thư viện cảm biến của hãng A trả về <code>int16_t</code> thô, của hãng B trả về <code>float</code> đã đổi đơn vị — viết adapter đưa về một interface <code>ISensor</code> chung.",
       "Bọc HAL của nhà sản xuất (STM32 HAL, ESP-IDF) sau interface của riêng bạn → đổi chip chỉ cần viết adapter mới.",
       "Bọc thư viện C (hàm + struct) thành lớp C++ (RAII) cũng là một dạng adapter."],
  cpp_real=["<code>std::stack</code>, <code>std::queue</code> — “container adapter” bọc <code>std::deque</code>", "<code>std::back_inserter</code> (iterator adapter)", "Arduino core cho ESP32: bọc API ESP-IDF thành API Arduino"],
  py_real=["<code>io.TextIOWrapper</code> bọc luồng byte thành luồng văn bản", "<code>csv.DictReader</code>"],
),
"bridge": dict(
  cpp=["<code>RemoteControl</code> giữ <code>Device&amp; device_</code> — tham chiếu tới implementor chính là cây cầu.",
       "<code>using RemoteControl::RemoteControl;</code> giúp lớp con kế thừa constructor, khỏi viết lại.",
       "<code>std::clamp</code> (C++17) giới hạn âm lượng trong 0–100."],
  py=["Code gần như dịch 1–1; cây cầu là thuộc tính <code>self.device</code>.",
      "<code>Tv</code>, <code>Radio</code> chỉ cần <code>pass</code> vì đã kế thừa đủ hành vi từ <code>Device</code>."],
  emb=["Tách <b>logic ứng dụng</b> (điều khiển động cơ, hiển thị) khỏi <b>driver phần cứng</b> (L298N, DRV8833; OLED SSD1306, LCD1602): hai chiều thay đổi độc lập.",
       "Thư viện <b>Adafruit_GFX</b>: lớp vẽ chữ/hình (abstraction) ↔ hàng chục driver màn hình (implementation) — ví dụ kinh điển của Bridge.",
       "Giúp viết <b>unit test trên PC</b>: thay driver thật bằng driver giả (mock) mà không đổi code logic."],
  cpp_real=["Adafruit_GFX ↔ Adafruit_SSD1306 / ST7735 / ILI9341", "Kỹ thuật PIMPL (pointer to implementation) trong C++", "<code>Print</code> class của Arduino: <code>print()</code> ↔ <code>write()</code> của từng thiết bị"],
  py_real=["<code>logging</code>: <code>Logger</code> ↔ <code>Handler</code> (file, console, mạng)", "<code>pathlib</code>: <code>Path</code> ↔ <code>PosixPath</code>/<code>WindowsPath</code>"],
),
"composite": dict(
  cpp=["<code>Folder</code> <b>sở hữu</b> các con qua <code>std::vector&lt;std::unique_ptr&lt;FileSystemItem&gt;&gt;</code> — huỷ thư mục gốc sẽ tự huỷ cả cây (RAII).",
       "Hàm template <code>add&lt;T&gt;(args...)</code> tạo con ngay tại chỗ và trả về con trỏ thô (không sở hữu) để tiện thêm tiếp.",
       "<code>getSize()</code> và <code>print()</code> gọi đệ quy qua hàm ảo."],
  py=["<code>get_size()</code> chỉ một dòng nhờ <code>sum(...)</code> trên generator.",
      "<code>add()</code> trả về chính phần tử vừa thêm nên viết được <code>docs.add(Folder(\"images\")).add(...)</code>."],
  emb=["Hệ thống <b>menu nhiều cấp</b> trên màn hình LCD/OLED: menu chứa mục chọn và menu con, nút OK/Back duyệt cây.",
       "Cây giao diện của thư viện đồ hoạ (LVGL: <code>lv_obj</code> chứa các <code>lv_obj</code> con).",
       "Nhóm cảm biến: “Phòng” chứa nhiều cảm biến; <code>readAverage()</code> trên phòng = trung bình các con.",
       "Trên MCU RAM nhỏ, có thể dựng cây tĩnh bằng mảng thay vì cấp phát động."],
  cpp_real=["LVGL: cây <code>lv_obj_t</code>", "Qt: <code>QObject</code> cha – con", "ArduinoJson: <code>JsonObject</code> chứa <code>JsonVariant</code>"],
  py_real=["<code>xml.etree.ElementTree</code>", "Tkinter: widget chứa widget", "<code>ast</code> module (cây cú pháp)"],
),
"decorator": dict(
  cpp=["Decorator <b>sở hữu</b> đối tượng được bọc qua <code>std::unique_ptr&lt;Drink&gt; inner_</code> — huỷ lớp ngoài cùng sẽ huỷ cả chồng.",
       "<code>make_unique&lt;Pearl&gt;(make_unique&lt;CheeseFoam&gt;(make_unique&lt;MilkTea&gt;()))</code> — đọc từ trong ra ngoài.",
       "<code>using ToppingDecorator::ToppingDecorator;</code> kế thừa constructor."],
  py=["Mẫu Decorator (bọc <b>đối tượng</b> lúc chạy) khác với cú pháp <code>@decorator</code> của Python (bọc <b>hàm</b> lúc định nghĩa) — nhưng cùng một ý tưởng “bọc để thêm hành vi”.",
      "Ví dụ <code>@log_call</code> ở cuối file ghi log mỗi lần đọc cảm biến mà không sửa hàm <code>read_sensor</code>.",
      "<code>functools.wraps</code> giữ nguyên tên và docstring của hàm gốc."],
  emb=["Bọc luồng dữ liệu nhiều lớp: <code>Checksum(Encrypt(Compress(UartStream)))</code> — mỗi lớp một nhiệm vụ, bật/tắt tuỳ cấu hình.",
       "Bọc driver cảm biến để thêm <b>bộ lọc</b>: <code>MovingAverage(MedianFilter(AdcSensor))</code> — rất hữu ích khi tín hiệu ADC nhiễu.",
       "Thêm ghi log/đo thời gian thực thi cho một driver khi debug mà không sửa driver."],
  cpp_real=["Các lớp lọc tín hiệu trong thư viện DSP", "Boost.Iostreams filters", "Arduino <code>Stream</code> bọc bởi lớp đệm/nén"],
  py_real=["<code>@functools.lru_cache</code>, <code>@property</code>, <code>@staticmethod</code>", "<code>io.BufferedReader</code> bọc <code>FileIO</code>", "<code>gzip.GzipFile</code> bọc file object"],
),
"facade": dict(
  cpp=["Facade giữ <b>tham chiếu</b> tới các hệ thống con — các đối tượng phần cứng được tạo tĩnh một lần trong <code>main()</code>.",
       "Mỗi hệ thống con có chú thích cơ chế thật (PWM, mã IR, động cơ bước) để thấy Facade che giấu bao nhiêu chi tiết."],
  py=["Facade tự tạo các hệ thống con trong <code>__init__</code> — cách đơn giản khi không cần thay thế chúng.",
      "<code>leave_home()</code> gọi <code>off()</code> trên một tuple thiết bị nhờ duck typing."],
  emb=["Gần như mọi thư viện Arduino là Facade: <code>WiFi.begin(ssid, pass)</code> che giấu hàng trăm dòng ESP-IDF (event loop, netif, DHCP…).",
       "<code>digitalWrite(pin, HIGH)</code> che giấu thao tác thanh ghi <code>GPIOx-&gt;BSRR</code>.",
       "Trong dự án robot: lớp <code>Robot</code> với <code>forward()</code>, <code>turnLeft()</code> là facade cho 2 driver động cơ + encoder + IMU."],
  cpp_real=["Arduino API (<code>digitalWrite</code>, <code>analogRead</code>, <code>WiFi</code>)", "ESP-IDF <code>esp_wifi</code>", "Thư viện <code>Servo.h</code>"],
  py_real=["<code>requests.get()</code> che giấu <code>urllib3</code>", "<code>shutil.copytree()</code>", "MicroPython <code>network.WLAN</code>"],
),
"flyweight": dict(
  cpp=["<code>Tree</code> chỉ còn <code>short x, y</code> + một con trỏ — <code>sizeof(Tree)</code> in ra 16 byte (8 byte con trỏ + padding).",
       "<code>TreeFactory</code> trả về <code>const TreeType*</code>: con trỏ tới hằng nhấn mạnh flyweight là <b>bất biến</b>.",
       "<code>std::mt19937 rng(42)</code> seed cố định để kết quả lặp lại."],
  py=["<code>@lru_cache(maxsize=None)</code> biến hàm thành Flyweight Factory chỉ với một dòng; <code>cache_info()</code> cho biết 99 997 lần lấy lại từ cache.",
      "<code>__slots__</code> loại bỏ <code>__dict__</code> của từng đối tượng — giảm đáng kể bộ nhớ khi có hàng trăm nghìn đối tượng (cũng hữu ích trên MicroPython)."],
  emb=["Font chữ và icon bitmap trên màn hình OLED/TFT: dữ liệu glyph nằm <b>một lần trong Flash</b> (<code>PROGMEM</code>/<code>const</code>), mỗi ký tự hiển thị chỉ lưu vị trí + con trỏ.",
       "Chuỗi hằng trong Flash (<code>F(\"...\")</code> trên AVR) thay vì nhân bản vào RAM.",
       "Bảng tra (lookup table) dùng chung: sin/cos, hệ số lọc, bảng CRC."],
  cpp_real=["Font của Adafruit_GFX / U8g2 lưu trong <code>PROGMEM</code>", "<code>std::string_view</code> trỏ vào chuỗi dùng chung", "Bảng CRC <code>const</code> trong Flash"],
  py_real=["<code>sys.intern()</code>", "Cache số nguyên nhỏ (-5…256) của CPython", "<code>functools.lru_cache</code>"],
),
"proxy": dict(
  cpp=["Virtual proxy giữ <code>std::unique_ptr&lt;RealImage&gt;</code> rỗng cho tới lần <code>display()</code> đầu tiên.",
       "Protection + caching proxy giữ <b>tham chiếu</b> tới dịch vụ thật dùng chung; cache là <code>std::map</code>.",
       "Smart pointer trong C++ (<code>unique_ptr</code>, <code>shared_ptr</code>) bản thân chúng chính là một dạng proxy."],
  py=["<code>__getattr__</code> chuyển mọi thuộc tính/phương thức chưa định nghĩa sang đối tượng thật — viết proxy tổng quát rất gọn.",
      "Proxy không cần kế thừa từ lớp thật nhờ duck typing."],
  emb=["<b>Remote proxy</b>: lớp <code>RemoteSensor</code> trên điện thoại/PC có cùng interface với cảm biến, nhưng bên trong gửi lệnh qua Bluetooth/MQTT tới ESP32.",
       "<b>Caching proxy</b>: đọc cảm biến chậm (DHT22 cần ≥ 2 giây giữa hai lần đọc) → proxy trả giá trị cũ nếu chưa đủ thời gian.",
       "<b>Protection proxy</b>: chặn ghi vào vùng Flash/EEPROM quan trọng khi chưa mở khoá."],
  cpp_real=["<code>std::unique_ptr</code>, <code>std::shared_ptr</code>", "<code>std::vector&lt;bool&gt;::reference</code>", "Thư viện DHT của Adafruit (giới hạn tần suất đọc)"],
  py_real=["<code>weakref.proxy()</code>", "<code>unittest.mock.Mock</code>", "<code>xmlrpc.client.ServerProxy</code> (remote proxy)"],
),
"chain-of-responsibility": dict(
  cpp=["<code>setNext()</code> trả về <code>Approver&amp;</code> để nối chuỗi; con trỏ <code>next_</code> là con trỏ <b>không sở hữu</b>.",
       "<code>handle()</code> không phải hàm ảo → lớp con không thể ghi đè logic chuyển tiếp (tương đương <code>final</code>).",
       "Ba handler là biến cục bộ trong <code>main()</code> — chuỗi không cần cấp phát động.",
       "Yêu cầu là <code>struct LeaveRequest</code>, khởi tạo gọn bằng <code>{\"Cô Lan\", 1, \"...\"}</code>."],
  py=["<code>role</code> là thuộc tính lớp, mỗi lớp con ghi đè một giá trị.",
      "<code>@dataclass(frozen=True)</code> cho đối tượng yêu cầu bất biến."],
  emb=["Xử lý lệnh nhận qua UART: chuỗi <code>LedCommandHandler → MotorCommandHandler → ConfigCommandHandler → UnknownHandler</code>; mỗi handler kiểm tra tiền tố lệnh.",
       "Xử lý ngắt/sự kiện theo mức ưu tiên; bộ lọc gói tin mạng.",
       "Middleware của web server trên ESP32 (xác thực → giới hạn tần suất → xử lý)."],
  cpp_real=["ESP-IDF <code>esp_http_server</code>: chuỗi URI handler", "Bảng vector ngắt dùng chung (shared IRQ)", "Qt: sự kiện lan truyền từ widget con lên cha"],
  py_real=["Middleware của Django / Flask (WSGI)", "<code>logging</code>: log lan truyền lên logger cha", "Chuỗi <code>except</code> trong <code>try</code>"],
),
"command": dict(
  cpp=["Lịch sử là <code>std::stack&lt;std::unique_ptr&lt;Command&gt;&gt;</code> — command bị pop sẽ tự giải phóng.",
       "Command giữ <b>tham chiếu</b> tới receiver (<code>Light&amp;</code>, <code>Fan&amp;</code>), không sở hữu thiết bị.",
       "<code>FanSpeedCommand</code> lưu <code>prevSpeed_</code> lúc <code>execute()</code> để <code>undo()</code> khôi phục chính xác."],
  py=["Lịch sử chỉ là một <code>list</code> dùng <code>append</code>/<code>pop</code> như ngăn xếp.",
      "Khi không cần undo, command trong Python thường chỉ là một hàm hoặc <code>functools.partial</code>."],
  emb=["Lệnh từ app điện thoại/Bluetooth/UART được <b>đóng gói thành Command</b> và đưa vào hàng đợi (FreeRTOS queue); task xử lý lấy ra thực thi tuần tự — tách phần nhận lệnh khỏi phần điều khiển phần cứng.",
       "Ghi và phát lại <b>macro</b>: robot học chuỗi chuyển động rồi lặp lại.",
       "Bảng ánh xạ phím IR remote → Command cho phép gán lại nút mà không sửa code xử lý."],
  cpp_real=["FreeRTOS queue chứa struct lệnh", "<code>std::function</code> trong hàng đợi tác vụ", "Qt: <code>QUndoCommand</code>, <code>QUndoStack</code>"],
  py_real=["<code>functools.partial</code>", "<code>concurrent.futures</code> (submit tác vụ)", "Tkinter: <code>command=</code> của nút bấm"],
),
"interpreter": dict(
  cpp=["Một lớp template <code>BinaryExpr&lt;char Op&gt;</code> + <code>if constexpr</code> thay cho ba lớp riêng — trình biên dịch sinh ra ba lớp khi cần.",
       "AST sở hữu các nút con qua <code>std::unique_ptr</code>; parser dùng <code>std::stack</code>.",
       "<code>Context</code> là <code>std::map&lt;std::string,int&gt;</code> chứa giá trị biến."],
  py=["<code>@dataclass</code> giúp mỗi nút cây chỉ vài dòng; bảng <code>OPS</code> ánh xạ toán tử → lambda.",
      "Python có sẵn <code>ast</code> và <code>eval</code> nhưng <b>không bao giờ</b> nên <code>eval</code> chuỗi do người dùng gửi tới — tự viết interpreter nhỏ an toàn hơn."],
  emb=["Firmware nhận <b>công thức/luật</b> qua Serial hoặc MQTT (“bật quạt khi <code>t 30 &gt;</code>”) và thực thi mà không cần nạp lại chương trình.",
       "Bộ thông dịch lệnh AT của module SIM/ESP8266; G-code trong máy in 3D/CNC (Marlin, GRBL) là ví dụ thực tế lớn.",
       "Ngôn ngữ kịch bản nhỏ cho robot: <code>FORWARD 10</code>, <code>TURN 90</code>."],
  cpp_real=["Marlin / GRBL: thông dịch G-code", "Bộ xử lý lệnh AT", "<code>std::regex</code>"],
  py_real=["Module <code>ast</code>, <code>re</code>", "MicroPython chính là một trình thông dịch chạy trên MCU", "<code>string.Template</code>"],
),
"iterator": dict(
  cpp=["<code>Playlist::Iterator</code> chỉ cần 3 toán tử <code>*</code>, <code>++</code>, <code>!=</code> cùng <code>begin()</code>/<code>end()</code> là dùng được <b>range-for</b>.",
       "Dữ liệu nằm trong <code>std::array</code> kích thước cố định (template <code>Capacity</code>) — kiểu bộ đệm tĩnh quen thuộc trên MCU.",
       "<code>ReverseIterator</code> viết kiểu <code>hasNext()/next()</code> để so sánh với cách của Java."],
  py=["<code>ForwardIterator</code> cài đặt giao thức <code>__iter__</code>/<code>__next__</code> và ném <code>StopIteration</code> khi hết.",
      "<code>reverse()</code> là <b>generator</b> (dùng <code>yield</code>) — cách viết iterator ngắn nhất.",
      "Có thể gọi <code>next(it)</code> thủ công rồi tiếp tục <code>for</code> trên cùng iterator."],
  emb=["Duyệt <b>bộ đệm vòng</b> (ring buffer) chứa mẫu ADC mà không lộ chỉ số head/tail.",
       "Duyệt danh sách thiết bị trên bus I2C/1-Wire (<code>OneWire::search()</code>) hoặc các bản ghi log trong Flash.",
       "Iterator giúp dùng lại thuật toán STL (<code>std::accumulate</code>, <code>std::max_element</code>) trên cấu trúc tự viết."],
  cpp_real=["Toàn bộ STL: <code>std::vector::iterator</code>, <code>std::map::iterator</code>…", "ArduinoJson: duyệt <code>JsonArray</code>", "OneWire search"],
  py_real=["<code>for</code>, <code>range</code>, <code>enumerate</code>, <code>zip</code>", "Module <code>itertools</code>", "Đối tượng file (duyệt từng dòng)"],
),
"mediator": dict(
  cpp=["<code>User</code> giữ <code>ChatRoom&amp; room_</code>; mediator giữ <code>std::vector&lt;User*&gt;</code> (không sở hữu).",
       "Constructor của <code>User</code> tự gọi <code>room_.join(*this)</code>.",
       "Kiểm tra vai trò bằng hàm ảo <code>isTeacher()</code> thay cho <code>dynamic_cast</code>."],
  py=["Dùng <code>isinstance(sender, Teacher)</code> để áp quy tắc ghim tin.",
      "Mediator không cần lớp trừu tượng riêng nhờ duck typing."],
  emb=["<b>MQTT broker</b> là Mediator giữa các thiết bị IoT: cảm biến publish, màn hình/relay subscribe — không thiết bị nào biết nhau.",
       "Bộ điều phối trong robot: nhận dữ liệu từ cảm biến, ra quyết định và ra lệnh cho các cơ cấu chấp hành, thay vì để cảm biến gọi thẳng động cơ.",
       "Event bus trong firmware (ESP-IDF <code>esp_event</code>)."],
  cpp_real=["ESP-IDF <code>esp_event</code> loop", "Mosquitto (MQTT broker)", "Qt: signal/slot qua đối tượng điều phối"],
  py_real=["<code>asyncio</code> event loop", "Paho-MQTT client + broker", "Tkinter: controller điều phối widget"],
),
"memento": dict(
  cpp=["<code>Editor::Memento</code> có <b>mọi thành viên private</b> và khai báo <code>friend class Editor</code> — chỉ Editor đọc được; <code>History</code> giữ memento nhưng truy cập vào trong sẽ <b>lỗi biên dịch</b>.",
       "Đây là cách C++ thực thi đúng tinh thần “không phá vỡ đóng gói” của mẫu.",
       "Lịch sử là <code>std::stack&lt;Editor::Memento&gt;</code>, lưu theo giá trị."],
  py=["<code>NamedTuple</code> lồng trong lớp → memento bất biến.",
      "Python không có private thật; dấu <code>_</code> là quy ước “đừng chạm vào”."],
  emb=["Trước khi thử bộ thông số PID mới, lưu memento cấu hình cũ; robot chạy không ổn thì khôi phục.",
       "Lưu memento xuống <b>EEPROM/Flash</b> (struct cấu hình + CRC) để giữ trạng thái qua lần mất điện; khi khởi động đọc lại.",
       "Cập nhật firmware OTA dùng hai phân vùng — phân vùng cũ là “memento” để rollback khi bản mới lỗi."],
  cpp_real=["Arduino <code>EEPROM.put()</code>/<code>EEPROM.get()</code> với struct cấu hình", "ESP-IDF NVS (Non-Volatile Storage)", "Cơ chế rollback OTA của ESP32"],
  py_real=["<code>pickle</code>, <code>copy.deepcopy</code>", "<code>json.dump</code> trạng thái", "Lệnh undo của IDLE"],
),
"observer": dict(
  cpp=["Danh sách observer là <code>std::array&lt;Observer*, 8&gt;</code> cố định — không cấp phát; <code>subscribe()</code> trả về <code>false</code> khi hết chỗ.",
       "<code>setMeasurements()</code> được gọi từ <code>loop()</code> sau khi đọc cảm biến, rồi tự động thông báo.",
       "Lưu ý: observer phải sống lâu hơn subject hoặc tự <code>unsubscribe()</code> trước khi bị huỷ — nếu không sẽ có con trỏ treo."],
  py=["Observer chỉ cần là <b>callable</b>: một hàm thường (<code>lcd_display</code>), một closure (<code>make_phone_app</code>) hoặc đối tượng có <code>__call__</code> (<code>AutoFan</code>).",
      "Không cần interface — gọn hơn nhiều so với C++/Java."],
  emb=["Một cảm biến, nhiều nơi cần dữ liệu (màn hình, relay, thẻ SD, MQTT) — đúng bài toán của Observer.",
       "Callback ngắt (<code>attachInterrupt</code>) và event của ESP-IDF là dạng observer.",
       "Cẩn thận: <code>update()</code> gọi trong ngữ cảnh ngắt (ISR) phải cực ngắn — thường chỉ đặt cờ hoặc đẩy vào hàng đợi, xử lý sau trong task."],
  cpp_real=["Arduino <code>attachInterrupt(pin, callback, mode)</code>", "ESP-IDF <code>esp_event_handler_register</code>", "Qt signal/slot; Boost.Signals2"],
  py_real=["Tkinter <code>bind()</code>, <code>trace_add()</code>", "Paho-MQTT <code>on_message</code>", "MicroPython <code>Pin.irq(handler=...)</code>"],
),
"state": dict(
  cpp=["Các trạng thái <b>không có dữ liệu riêng</b> nên mỗi lớp chỉ có một thể hiện <code>static const</code> — chuyển trạng thái chỉ là đổi con trỏ, <b>không cấp phát</b>.",
       "Khai báo trước (<code>class VendingMachine;</code>), định nghĩa các hàm cần Context ở cuối file — kỹ thuật tách khai báo/định nghĩa để giải quyết phụ thuộc vòng.",
       "Hàm trạng thái nhận <code>VendingMachine&amp;</code> để có thể gọi <code>setState()</code>."],
  py=["Ba thể hiện dùng chung <code>NO_COIN</code>, <code>HAS_COIN</code>, <code>SOLD_OUT</code> ở mức module.",
      "Lớp cơ sở <code>State</code> có phương thức mặc định <code>...</code> nên lớp con chỉ ghi đè cái cần."],
  emb=["<b>Máy trạng thái hữu hạn (FSM)</b> là xương sống của firmware: đèn giao thông, robot dò line (FOLLOW → AVOID → STOP), máy giặt, giao thức truyền thông.",
       "Ba cách cài FSM trong C: <code>switch</code> trên <code>enum</code> (đơn giản), bảng chuyển trạng thái (mảng con trỏ hàm), và mẫu State hướng đối tượng (dễ mở rộng nhất).",
       "Kết hợp với <code>millis()</code> để mỗi trạng thái tự kiểm tra hết thời gian mà không dùng <code>delay()</code> chặn chương trình."],
  cpp_real=["Boost.MSM, Boost.SML (FSM bằng template)", "Trạng thái kết nối WiFi/BLE trong ESP-IDF", "Marlin: trạng thái máy in"],
  py_real=["Thư viện <code>transitions</code>", "<code>asyncio</code> trạng thái của Future/Task", "Trạng thái kết nối của <code>http.client</code>"],
),
"strategy": dict(
  cpp=["Ví dụ thể hiện <b>cả ba cách</b>: interface + hàm ảo (<code>checkout</code>), lambda/<code>std::function</code> (<code>total</code>), và template policy (<code>totalWith&lt;StudentDiscount&gt;()</code>).",
       "Policy là struct có hàm <code>static constexpr</code> — trình biên dịch có thể tính sẵn và inline, không tốn chi phí lúc chạy.",
       "Strategy được truyền bằng <code>const&amp;</code> — tạo tạm thời trên stack."],
  py=["Strategy thường chỉ là <b>một hàm</b>: <code>cart.total(lambda p: p * 90 // 100)</code>.",
      "Tham số mặc định <code>discount=lambda p: p</code> là strategy “không làm gì”."],
  emb=["Thuật toán điều khiển động cơ hoán đổi được: Bang-bang, P, PID — chọn qua cấu hình hoặc lệnh Bluetooth.",
       "Bộ lọc tín hiệu cảm biến: trung bình trượt, median, Kalman — cùng interface <code>filter(sample)</code>.",
       "Chiến lược tiết kiệm năng lượng: luôn bật, ngủ nhẹ, ngủ sâu theo mức pin."],
  cpp_real=["<code>std::sort(begin, end, comparator)</code>", "Tham số <code>Allocator</code>, <code>Hash</code>, <code>Compare</code> của container STL (policy)", "Thư viện PID_v1 với các chế độ"],
  py_real=["<code>sorted(data, key=...)</code>", "<code>max(..., key=...)</code>", "scikit-learn: tham số <code>solver=</code>"],
),
"template-method": dict(
  cpp=["<code>generate()</code> <b>không</b> phải hàm ảo nên lớp con không ghi đè được trình tự (tương đương <code>final</code>).",
       "Các bước bắt buộc là hàm <b>thuần ảo</b> <code>= 0</code>; hook là hàm ảo có cài đặt mặc định.",
       "Đặt các bước ở <code>protected</code> để client chỉ thấy <code>generate()</code> (idiom <i>Non-Virtual Interface</i> — NVI)."],
  py=["Python không có <code>final</code> thật cho phương thức; đặt tên rõ ràng và tài liệu hoá rằng <code>generate()</code> không nên ghi đè.",
      "<code>@abstractmethod</code> buộc lớp con cài các bước bắt buộc."],
  emb=["Khung <b>Arduino</b> chính là Template Method: lõi Arduino viết sẵn <code>main()</code> gọi <code>init()</code>, <code>setup()</code>, rồi lặp <code>loop()</code> — bạn chỉ điền các bước.",
       "Lớp trừu tượng <code>SensorTask</code> với <code>run()</code> = <code>wake() → measure() → filter() → publish() → sleep()</code>; mỗi cảm biến chỉ cài <code>measure()</code>.",
       "Quy trình hiệu chuẩn: các bước giống nhau, chỉ khác cách đọc giá trị chuẩn."],
  cpp_real=["Arduino core <code>main.cpp</code> gọi <code>setup()</code>/<code>loop()</code>", "Google Test: <code>SetUp()</code> → test → <code>TearDown()</code>", "Qt: <code>QThread::run()</code>"],
  py_real=["<code>unittest.TestCase</code>: <code>setUp</code>/<code>tearDown</code>", "<code>threading.Thread.run()</code>", "<code>socketserver.BaseRequestHandler.handle()</code>"],
),
"visitor": dict(
  cpp=["<b>Double dispatch</b>: <code>s-&gt;accept(v)</code> chọn lớp phần tử qua hàm ảo, rồi <code>v.visit(*this)</code> chọn đúng overload theo kiểu tĩnh của <code>*this</code>.",
       "Cuối file là cách <b>hiện đại</b>: <code>std::variant</code> + <code>std::visit</code> với mẫu <code>overloaded</code> — không hàm ảo, không heap, và trình biên dịch <b>báo lỗi nếu thiếu</b> trường hợp.",
       "Hằng <code>PI</code> tự định nghĩa vì <code>M_PI</code> không thuộc chuẩn C++."],
  py=["Python không nạp chồng theo kiểu nên dùng quy ước tên <code>visit_circle</code>, <code>visit_rectangle</code> và <code>getattr</code> để dispatch (giống cách module <code>ast.NodeVisitor</code> làm).",
      "Cách hiện đại: <code>match/case</code> (Python 3.10+) với mẫu cấu trúc <code>Circle(r=r)</code>."],
  emb=["Trên cấu trúc cấu hình phức tạp (cây menu, danh sách thiết bị) cần nhiều thao tác: xuất JSON gửi app, lưu EEPROM, in ra Serial — mỗi thao tác một visitor.",
       "<code>std::variant</code> rất hợp với firmware: biểu diễn các loại gói tin/sự kiện khác nhau trong một hàng đợi kích thước cố định, xử lý bằng <code>std::visit</code>."],
  cpp_real=["<code>std::visit</code> (C++17)", "Clang AST: <code>RecursiveASTVisitor</code>", "Boost.Variant"],
  py_real=["<code>ast.NodeVisitor</code>", "<code>functools.singledispatch</code>", "<code>os.walk</code> + hàm xử lý"],
),
}
